<?xml version="1.0" encoding="utf-8"?>
<!--
This file was generated by Altova MapForce 2008r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:n="http://schemas.microsoft.com/dynamics/2008/01/documents/CustInvoiceJour_GRD" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="n xs xsi xsl">
	<xsl:output method="xml" encoding="windows-1251" indent="yes" />
	<xsl:template match="/n:CustInvoiceJour_GRD">
		<Файл>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">
				<xsl:value-of select="'C:/BTS/XSD/FNS/DP_OTORG12_1_986_00_05_01_01.xsd'" />
			</xsl:attribute>
			<xsl:for-each select="n:CustInvoiceJour">
				<xsl:for-each select="n:GRD_EdoFileName">
					<xsl:variable name="Vvar1083_GRD_EdoFileName_string" select="string(.)" />
					<xsl:attribute name="ИдФайл">
						<xsl:value-of select="$Vvar1083_GRD_EdoFileName_string" />
					</xsl:attribute>
				</xsl:for-each>
			</xsl:for-each>
			<xsl:for-each select="n:CustInvoiceJour">
				<xsl:for-each select="n:GRD_EdoProgramVersion">
					<xsl:variable name="Vvar1090_GRD_EdoProgramVersion_string" select="string(.)" />
					<xsl:attribute name="ВерсПрог">
						<xsl:value-of select="$Vvar1090_GRD_EdoProgramVersion_string" />
					</xsl:attribute>
				</xsl:for-each>
			</xsl:for-each>
			<xsl:for-each select="n:CustInvoiceJour">
				<xsl:for-each select="n:GRD_EdoFormatVersion">
					<xsl:variable name="Vvar1097_GRD_EdoFormatVersion_string" select="string(.)" />
					<xsl:attribute name="ВерсФорм">
						<xsl:value-of select="$Vvar1097_GRD_EdoFormatVersion_string" />
					</xsl:attribute>
				</xsl:for-each>
			</xsl:for-each>
			<СвУчДокОбор>
				<xsl:for-each select="n:CustInvoiceJour">
					<xsl:for-each select="n:GRD_EdoSenderId">
						<xsl:variable name="Vvar1104_GRD_EdoSenderId_string" select="string(.)" />
						<xsl:attribute name="ИдОтпр">
							<xsl:value-of select="$Vvar1104_GRD_EdoSenderId_string" />
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n:CustInvoiceJour">
					<xsl:for-each select="n:GRD_EdoBuyerId">
						<xsl:variable name="Vvar1111_GRD_EdoBuyerId_string" select="string(.)" />
						<xsl:attribute name="ИдПок">
							<xsl:value-of select="$Vvar1111_GRD_EdoBuyerId_string" />
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<СвОЭДОтпрСФ>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoCompanyName">
							<xsl:variable name="Vvar1118_GRD_EdoCompanyName_string" select="string(.)" />
							<xsl:attribute name="НаимОрг">
								<xsl:value-of select="$Vvar1118_GRD_EdoCompanyName_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoCompanyINN">
							<xsl:variable name="Vvar1125_GRD_EdoCompanyINN_string" select="string(.)" />
							<xsl:attribute name="ИННЮЛ">
								<xsl:value-of select="$Vvar1125_GRD_EdoCompanyINN_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoId">
							<xsl:variable name="Vvar1132_GRD_EdoId_string" select="string(.)" />
							<xsl:attribute name="ИдЭДОСФ">
								<xsl:value-of select="$Vvar1132_GRD_EdoId_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
				</СвОЭДОтпрСФ>
			</СвУчДокОбор>
			<Документ>
				<xsl:for-each select="n:CustInvoiceJour">
					<xsl:for-each select="n:GRD_EdoKND">
						<xsl:variable name="Vvar1139_GRD_EdoKND_string" select="string(.)" />
						<xsl:attribute name="КНД">
							<xsl:value-of select="$Vvar1139_GRD_EdoKND_string" />
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n:CustInvoiceJour">
					<xsl:for-each select="n:GRD_EdoDocDate">
						<xsl:variable name="Vvar1146_GRD_EdoDocDate_string" select="string(.)" />
						<xsl:attribute name="ДатаДок">
							<xsl:value-of select="$Vvar1146_GRD_EdoDocDate_string" />
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n:CustInvoiceJour">
					<xsl:for-each select="n:GRD_EdoDocTime">
						<xsl:variable name="Vvar1153_GRD_EdoDocTime_string" select="string(.)" />
						<xsl:attribute name="ВремДок">
							<xsl:value-of select="$Vvar1153_GRD_EdoDocTime_string" />
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				
				<СвТНО>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoOrigDocName">
							<xsl:variable name="Vvar1160_GRD_EdoOrigDocName_string" select="string(.)" />
							<xsl:attribute name="НаимПервДок">
								<xsl:value-of select="$Vvar1160_GRD_EdoOrigDocName_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoOrigDocOKUD">
							<xsl:variable name="Vvar1167_GRD_EdoOrigDocOKUD_string" select="string(.)" />
							<xsl:attribute name="ОКУДПервДок">
								<xsl:value-of select="$Vvar1167_GRD_EdoOrigDocOKUD_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n:CustInvoiceJour">
						<xsl:for-each select="n:GRD_EdoFormatNum">
							<xsl:variable name="Vvar1174_GRD_EdoFormatNum_string" select="string(.)" />
							<xsl:attribute name="НомФорм">
								<xsl:value-of select="$Vvar1174_GRD_EdoFormatNum_string" />
							</xsl:attribute>
						</xsl:for-each>
					</xsl:for-each>
					<ГрузОт>
						<ГрузОтпр>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoConsignorOKPO">
									<xsl:variable name="Vvar1181_GRD_EdoConsignorOKPO_string" select="string(.)" />
									<xsl:attribute name="ОКПО">
										<xsl:value-of select="$Vvar1181_GRD_EdoConsignorOKPO_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<ИдСв>
								<СвЮЛ>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorName">
											<xsl:variable name="Vvar1188_GRD_EdoConsignorName_string" select="string(.)" />
											<xsl:attribute name="НаимОрг">
												<xsl:value-of select="$Vvar1188_GRD_EdoConsignorName_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorINN">
											<xsl:variable name="Vvar1195_GRD_EdoConsignorINN_string" select="string(.)" />
											<xsl:attribute name="ИННЮЛ">
												<xsl:value-of select="$Vvar1195_GRD_EdoConsignorINN_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorKPP">
											<xsl:variable name="Vvar1202_GRD_EdoConsignorKPP_string" select="string(.)" />
											<xsl:attribute name="КПП">
												<xsl:value-of select="$Vvar1202_GRD_EdoConsignorKPP_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
								</СвЮЛ>
							</ИдСв>
							<Адрес>
								<АдрТекст>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorAddress">
											<xsl:variable name="Vvar1209_GRD_EdoConsignorAddress_string" select="string(.)" />											
												<xsl:value-of select="$Vvar1209_GRD_EdoConsignorAddress_string" />
											</xsl:for-each>
									</xsl:for-each>
									
								</АдрТекст>
							</Адрес>
							<Контакт>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsignorPhone">
										<xsl:variable name="Vvar1272_GRD_EdoConsignorPhone_string" select="string(.)" />
										<xsl:attribute name="Тлф">
											<xsl:value-of select="$Vvar1272_GRD_EdoConsignorPhone_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsignorTeleFax">
										<xsl:variable name="Vvar1279_GRD_EdoConsignorTeleFax_string" select="string(.)" />
										<xsl:attribute name="Факс">
											<xsl:value-of select="$Vvar1279_GRD_EdoConsignorTeleFax_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</Контакт>
							<БанкРекв>
							<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorBankAccNum">
											<xsl:variable name="Vvar1286_GRD_EdoConsignorBankAccNum_string" select="string(.)" />
											<xsl:attribute name="НомерСчета">
												<xsl:value-of select="$Vvar1286_GRD_EdoConsignorBankAccNum_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
								<СвБанк>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorBankName">
											<xsl:variable name="Vvar1286_GRD_EdoConsignorBankName_string" select="string(.)" />
											<xsl:attribute name="НаимБанк">
												<xsl:value-of select="$Vvar1286_GRD_EdoConsignorBankName_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
									<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsignorBankBIC">
											<xsl:variable name="Vvar1293_GRD_EdoConsignorBankBIC_string" select="string(.)" />
											<xsl:attribute name="БИК">
												<xsl:value-of select="$Vvar1293_GRD_EdoConsignorBankBIC_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
								</СвБанк>
							</БанкРекв>
						</ГрузОтпр>
					</ГрузОт>
					<ГрузПолуч>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoConsigneeOKPO">
								<xsl:variable name="Vvar1300_GRD_EdoConsigneeOKPO_string" select="string(.)" />
								<xsl:attribute name="ОКПО">
									<xsl:value-of select="$Vvar1300_GRD_EdoConsigneeOKPO_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<ИдСв>
							<СвЮЛ>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeName">
										<xsl:variable name="Vvar1307_GRD_EdoConsigneeName_string" select="string(.)" />
										<xsl:attribute name="НаимОрг">
											<xsl:value-of select="$Vvar1307_GRD_EdoConsigneeName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeINN">
										<xsl:variable name="Vvar1314_GRD_EdoConsigneeINN_string" select="string(.)" />
										<xsl:attribute name="ИННЮЛ">
											<xsl:value-of select="$Vvar1314_GRD_EdoConsigneeINN_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeKPP">
										<xsl:variable name="Vvar1321_GRD_EdoConsigneeKPP_string" select="string(.)" />
										<xsl:attribute name="КПП">
											<xsl:value-of select="$Vvar1321_GRD_EdoConsigneeKPP_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвЮЛ>
						</ИдСв>
						<Адрес>
							<АдрТекст>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeAddress">
										<xsl:variable name="Vvar1328_GRD_EdoConsigneeAddress_string" select="string(.)" />										
											<xsl:value-of select="$Vvar1328_GRD_EdoConsigneeAddress_string" />										
									</xsl:for-each>
								</xsl:for-each>								
							</АдрТекст>
						</Адрес>
						<Контакт>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoConsigneePhone">
									<xsl:variable name="Vvar1391_GRD_EdoConsigneePhone_string" select="string(.)" />
									<xsl:attribute name="Тлф">
										<xsl:value-of select="$Vvar1391_GRD_EdoConsigneePhone_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoConsigneeTeleFax">
									<xsl:variable name="Vvar1398_GRD_EdoConsigneeTeleFax_string" select="string(.)" />
									<xsl:attribute name="Факс">
										<xsl:value-of select="$Vvar1398_GRD_EdoConsigneeTeleFax_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</Контакт>
						<БанкРекв>
						<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoConsigneeBankAccNum">
											<xsl:variable name="Vvar1286_GRD_EdoConsigneeBankAccNum_string" select="string(.)" />
											<xsl:attribute name="НомерСчета">
												<xsl:value-of select="$Vvar1286_GRD_EdoConsigneeBankAccNum_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
							<СвБанк>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeBankName">
										<xsl:variable name="Vvar1405_GRD_EdoConsigneeBankName_string" select="string(.)" />
										<xsl:attribute name="НаимБанк">
											<xsl:value-of select="$Vvar1405_GRD_EdoConsigneeBankName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoConsigneeBankBIC">
										<xsl:variable name="Vvar1412_GRD_EdoConsigneeBankBIC_string" select="string(.)" />
										<xsl:attribute name="БИК">
											<xsl:value-of select="$Vvar1412_GRD_EdoConsigneeBankBIC_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвБанк>
						</БанкРекв>
					</ГрузПолуч>
					<Поставщик>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoSupplierOKPO">
								<xsl:variable name="Vvar1419_GRD_EdoSupplierOKPO_string" select="string(.)" />
								<xsl:attribute name="ОКПО">
									<xsl:value-of select="$Vvar1419_GRD_EdoSupplierOKPO_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<ИдСв>
							<СвЮЛ>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierName">
										<xsl:variable name="Vvar1426_GRD_EdoSupplierName_string" select="string(.)" />
										<xsl:attribute name="НаимОрг">
											<xsl:value-of select="$Vvar1426_GRD_EdoSupplierName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierINN">
										<xsl:variable name="Vvar1433_GRD_EdoSupplierINN_string" select="string(.)" />
										<xsl:attribute name="ИННЮЛ">
											<xsl:value-of select="$Vvar1433_GRD_EdoSupplierINN_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierKPP">
										<xsl:variable name="Vvar1440_GRD_EdoSupplierKPP_string" select="string(.)" />
										<xsl:attribute name="КПП">
											<xsl:value-of select="$Vvar1440_GRD_EdoSupplierKPP_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвЮЛ>
						</ИдСв>
						<Адрес>
							<АдрТекст>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierAddress">
										<xsl:variable name="Vvar1440_GRD_EdoSupplierAddress_string" select="string(.)" />
										<xsl:value-of select="$Vvar1440_GRD_EdoSupplierAddress_string" />
						  		</xsl:for-each>
								</xsl:for-each>
							</АдрТекст>
						</Адрес>
						<Контакт>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoSupplierPhone">
									<xsl:variable name="Vvar1510_GRD_EdoSupplierPhone_string" select="string(.)" />
									<xsl:attribute name="Тлф">
										<xsl:value-of select="$Vvar1510_GRD_EdoSupplierPhone_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoSupplierTeleFax">
									<xsl:variable name="Vvar1517_GRD_EdoSupplierTeleFax_string" select="string(.)" />
									<xsl:attribute name="Факс">
										<xsl:value-of select="$Vvar1517_GRD_EdoSupplierTeleFax_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</Контакт>
						<БанкРекв>
						<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoSupplierBankAccNum">
											<xsl:variable name="Vvar1286_GRD_EdoSupplierBankAccNum_string" select="string(.)" />
											<xsl:attribute name="НомерСчета">
												<xsl:value-of select="$Vvar1286_GRD_EdoSupplierBankAccNum_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
							<СвБанк>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierBankName">
										<xsl:variable name="Vvar1524_GRD_EdoSupplierBankName_string" select="string(.)" />
										<xsl:attribute name="НаимБанк">
											<xsl:value-of select="$Vvar1524_GRD_EdoSupplierBankName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoSupplierBankBIC">
										<xsl:variable name="Vvar1531_GRD_EdoSupplierBankBIC_string" select="string(.)" />
										<xsl:attribute name="БИК">
											<xsl:value-of select="$Vvar1531_GRD_EdoSupplierBankBIC_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвБанк>
						</БанкРекв>
					</Поставщик>
					<Плательщик>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoPayerOKPO">
								<xsl:variable name="Vvar1538_GRD_EdoPayerOKPO_string" select="string(.)" />
								<xsl:attribute name="ОКПО">
									<xsl:value-of select="$Vvar1538_GRD_EdoPayerOKPO_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<ИдСв>
							<СвЮЛ>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerName">
										<xsl:variable name="Vvar1545_GRD_EdoPayerName_string" select="string(.)" />
										<xsl:attribute name="НаимОрг">
											<xsl:value-of select="$Vvar1545_GRD_EdoPayerName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerINN">
										<xsl:variable name="Vvar1552_GRD_EdoPayerINN_string" select="string(.)" />
										<xsl:attribute name="ИННЮЛ">
											<xsl:value-of select="$Vvar1552_GRD_EdoPayerINN_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerKPP">
										<xsl:variable name="Vvar1559_GRD_EdoPayerKPP_string" select="string(.)" />
										<xsl:attribute name="КПП">
											<xsl:value-of select="$Vvar1559_GRD_EdoPayerKPP_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвЮЛ>
						</ИдСв>
						<Адрес>
							<АдрТекст>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerAddress">
										<xsl:variable name="Vvar1566_GRD_EdoPayerAddress_string" select="string(.)" />
											<xsl:value-of select="$Vvar1566_GRD_EdoPayerAddress_string" />										
									</xsl:for-each>
								</xsl:for-each>								
							</АдрТекст>
						</Адрес>
						<Контакт>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoPayerPhone">
									<xsl:variable name="Vvar1629_GRD_EdoPayerPhone_string" select="string(.)" />
									<xsl:attribute name="Тлф">
										<xsl:value-of select="substring($Vvar1629_GRD_EdoPayerPhone_string,1,20)" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoPayerTeleFax">
									<xsl:variable name="Vvar1636_GRD_EdoPayerTeleFax_string" select="string(.)" />
									<xsl:attribute name="Факс">
										<xsl:value-of select="$Vvar1636_GRD_EdoPayerTeleFax_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</Контакт>
						<БанкРекв>
						<xsl:for-each select="n:CustInvoiceJour">
										<xsl:for-each select="n:GRD_EdoPayerBankAccNum">
											<xsl:variable name="Vvar1286_GRD_EdoPayerBankAccNum_string" select="string(.)" />
											<xsl:attribute name="НомерСчета">
												<xsl:value-of select="$Vvar1286_GRD_EdoPayerBankAccNum_string" />
											</xsl:attribute>
										</xsl:for-each>
									</xsl:for-each>
							<СвБанк>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerBankName">
										<xsl:variable name="Vvar1643_GRD_EdoPayerBankName_string" select="string(.)" />
										<xsl:attribute name="НаимБанк">
											<xsl:value-of select="$Vvar1643_GRD_EdoPayerBankName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_EdoPayerBankBIC">
										<xsl:variable name="Vvar1650_GRD_EdoPayerBankBIC_string" select="string(.)" />
										<xsl:attribute name="БИК">
											<xsl:value-of select="$Vvar1650_GRD_EdoPayerBankBIC_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</СвБанк>
						</БанкРекв>
					</Плательщик>
					<Основание>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoInvoiceBaseName">
								<xsl:variable name="Vvar1657_GRD_EdoInvoiceBaseName_string" select="string(.)" />
								<xsl:attribute name="НаимОсн">
									<xsl:value-of select="$Vvar1657_GRD_EdoInvoiceBaseName_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoInvoiceBaseNum">
								<xsl:variable name="Vvar1664_GRD_EdoInvoiceBaseNum_string" select="string(.)" />
								<xsl:attribute name="НомОсн">
									<xsl:value-of select="$Vvar1664_GRD_EdoInvoiceBaseNum_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoInvoiceBaseDate">
								<xsl:variable name="Vvar1671_GRD_EdoInvoiceBaseDate_string" select="string(.)" />
								<xsl:attribute name="ДатаОсн">
									<xsl:value-of select="$Vvar1671_GRD_EdoInvoiceBaseDate_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
					</Основание>
					<ТН>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:InvoiceId">
								<xsl:variable name="Vvar1678_InvoiceId_string" select="string(.)" />
								<xsl:attribute name="НомТН">
									<xsl:value-of select="$Vvar1678_InvoiceId_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoInvoiceDate">
								<xsl:variable name="Vvar1685_GRD_EdoInvoiceDate_string" select="string(.)" />
								<xsl:attribute name="ДатаТН">
									<xsl:value-of select="$Vvar1685_GRD_EdoInvoiceDate_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<Таблица>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:CustInvoiceTrans">
									<СвТов>
										<xsl:for-each select="n:GRD_EdoLineNum">
											<xsl:variable name="Vvar1692_GRD_EdoLineNum_int" select="number(.)" />
											<xsl:attribute name="НомТов">
												<xsl:value-of select="number($Vvar1692_GRD_EdoLineNum_int)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:Name">
											<xsl:variable name="Vvar1698_Name_string" select="string(.)" />
											<xsl:attribute name="НаимТов">
												<xsl:value-of select="$Vvar1698_Name_string" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:ItemId">
											<xsl:variable name="Vvar1700_ItemId_anySimpleType" select="." />
											<xsl:attribute name="КодТов">
												<xsl:value-of select="string($Vvar1700_ItemId_anySimpleType)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:SalesUnit">
											<xsl:variable name="Vvar1704_SalesUnit_anySimpleType" select="." />
											<xsl:attribute name="НаимЕдИзм">
												<xsl:value-of select="string($Vvar1704_SalesUnit_anySimpleType)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:GRD_CodeOKEI">
											<xsl:variable name="Vvar1710_GRD_CodeOKEI_string" select="string(.)" />
											<xsl:attribute name="ОКЕИ_Тов">
												<xsl:value-of select="$Vvar1710_GRD_CodeOKEI_string" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:GRD_Packing">
											<xsl:variable name="Vvar1714_GRD_Packing_string" select="string(.)" />
											<xsl:attribute name="ВидУпак">
												<xsl:value-of select="$Vvar1714_GRD_Packing_string" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:GRD_TaxPackingQty">
											<xsl:variable name="Vvar1716_GRD_TaxPackingQty_decimal" select="number(.)" />
											<xsl:attribute name="Место">
												<xsl:value-of select="number($Vvar1716_GRD_TaxPackingQty_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:GRD_QtyNumber">
											<xsl:variable name="Vvar1720_GRD_QtyNumber_decimal" select="number(.)" />
											<xsl:attribute name="КолМест">
												<xsl:value-of select="number($Vvar1720_GRD_QtyNumber_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:GRD_GrossWeight">
											<xsl:variable name="Vvar1724_GRD_GrossWeight_decimal" select="number(.)" />
											<xsl:attribute name="Брутто">
												<xsl:value-of select="string($Vvar1724_GRD_GrossWeight_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:Qty">
											<xsl:variable name="Vvar1728_Qty_decimal" select="number(.)" />
											<xsl:attribute name="Нетто">
												<xsl:value-of select="string($Vvar1728_Qty_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:SalesPrice">
											<xsl:variable name="Vvar1732_SalesPrice_decimal" select="number(.)" />
											<xsl:attribute name="Цена">
												<xsl:value-of select="string($Vvar1732_SalesPrice_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:LineAmount">
											<xsl:variable name="Vvar1736_LineAmount_decimal" select="number(.)" />
											<xsl:attribute name="СумБезНДС">
												<xsl:value-of select="string($Vvar1736_LineAmount_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:VATValue_RU">
											<xsl:variable name="Vvar1740_VATValue_RU_decimal" select="number(.)" />
											<xsl:attribute name="СтавкаНДС">
												<xsl:value-of select="string($Vvar1740_VATValue_RU_decimal)" />
											</xsl:attribute>
										</xsl:for-each>
										<xsl:for-each select="n:TaxAmount">
											<xsl:variable name="Vvar1744_TaxAmount_decimal" select="number(.)" />
											<xsl:attribute name="СумНДС">
												<xsl:value-of select="string($Vvar1744_TaxAmount_decimal)" />
											</xsl:attribute>
										</xsl:for-each>

										 <xsl:if  test="not(n:LineAmountInclTax)">
          									 <xsl:attribute name="СумУчНДС">
												<xsl:value-of select="0.00" />											
											</xsl:attribute>
      									  </xsl:if>
										
																	
										<xsl:for-each select="n:LineAmountInclTax">
											<xsl:variable name="Vvar1748_LineAmountInclTax_decimal" select="number(.)" />
											<xsl:attribute name="СумУчНДС">
												<xsl:value-of select="string($Vvar1748_LineAmountInclTax_decimal)" />											
											</xsl:attribute>
										</xsl:for-each>
										
										
									</СвТов>
								</xsl:for-each>
							</xsl:for-each>
							<ВсегоНакл>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_TotalQtyNumber">
										<xsl:variable name="Vvar1755_GRD_TotalQtyNumber_decimal" select="number(.)" />
										<xsl:attribute name="КолМестВс">
											<xsl:value-of select="number($Vvar1755_GRD_TotalQtyNumber_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_TotalGrossWeight">
										<xsl:variable name="Vvar1762_GRD_TotalGrossWeight_decimal" select="number(.)" />
										<xsl:attribute name="БруттоВс">
											<xsl:value-of select="string($Vvar1762_GRD_TotalGrossWeight_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_TotalQty">
										<xsl:variable name="Vvar1769_GRD_TotalQty_decimal" select="number(.)" />
										<xsl:attribute name="НеттоВс">
											<xsl:value-of select="string($Vvar1769_GRD_TotalQty_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:InvoiceAmount">
										<xsl:variable name="Vvar1776_InvoiceAmount_decimal" select="number(.)" />
										<xsl:attribute name="СумБезНДСВс">
											<xsl:value-of select="string($Vvar1776_InvoiceAmount_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:SumTax">
										<xsl:variable name="Vvar1783_SumTax_decimal" select="number(.)" />
										<xsl:attribute name="СумНДСВс">
											<xsl:value-of select="string($Vvar1783_SumTax_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_InvoiceAmountInclTax">
										<xsl:variable name="Vvar1790_GRD_InvoiceAmountInclTax_decimal" select="number(.)" />
										<xsl:attribute name="СумУчНДСВс">
											<xsl:value-of select="string($Vvar1790_GRD_InvoiceAmountInclTax_decimal)" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</ВсегоНакл>
						</Таблица>
						<ТНОбщ>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_LinesQty">
									<xsl:variable name="Vvar1797_GRD_LinesQty_int" select="number(.)" />
									<xsl:attribute name="КолНомЗап">
										<xsl:value-of select="number($Vvar1797_GRD_LinesQty_int)" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_TotalQtyNumber">
									<xsl:variable name="Vvar1804_GRD_TotalQtyNumber_decimal" select="number(.)" />
									<xsl:attribute name="ВсМест">
										<xsl:value-of select="number($Vvar1804_GRD_TotalQtyNumber_decimal)" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_TotalQty">
									<xsl:variable name="Vvar1811_GRD_TotalQty_decimal" select="number(.)" />
									<xsl:attribute name="Нетто">
										<xsl:value-of select="string($Vvar1811_GRD_TotalQty_decimal)" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_TotalGrossWeight">
									<xsl:variable name="Vvar1818_GRD_TotalGrossWeight_decimal" select="number(.)" />
									<xsl:attribute name="Брутто">
										<xsl:value-of select="string($Vvar1818_GRD_TotalGrossWeight_decimal)" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</ТНОбщ>
					</ТН>
					<ОтпускГруз>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:InvoiceAmountStr">
								<xsl:variable name="Vvar1825_GRD_InvoiceAmountInclTax_decimal" select="normalize-space(.)" />
								<xsl:attribute name="СумОтпуск">
									<xsl:value-of select="$Vvar1825_GRD_InvoiceAmountInclTax_decimal" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoInvoiceDate">
								<xsl:variable name="Vvar1834_GRD_EdoInvoiceDate_string" select="string(.)" />
								<xsl:attribute name="ДатаОтпуск">
									<xsl:value-of select="$Vvar1834_GRD_EdoInvoiceDate_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<ОтпускРазреш>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_OfficialsTableDirTitle">
									<xsl:variable name="Vvar1841_GRD_OfficialsTableDirTitle_string" select="string(.)" />
									<xsl:attribute name="Должность">
										<xsl:value-of select="$Vvar1841_GRD_OfficialsTableDirTitle_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<ФИО>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableDirLastName">
										<xsl:variable name="Vvar1848_GRD_OfficialsTableDirLastName_string" select="string(.)" />
										<xsl:attribute name="Фамилия">
											<xsl:value-of select="$Vvar1848_GRD_OfficialsTableDirLastName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableDirFirstName">
										<xsl:variable name="Vvar1855_GRD_OfficialsTableDirFirstName_string" select="string(.)" />
										<xsl:attribute name="Имя">
											<xsl:value-of select="$Vvar1855_GRD_OfficialsTableDirFirstName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableDirMidName">
										<xsl:variable name="Vvar1862_GRD_OfficialsTableDirMiddleName_string" select="string(.)" />
										<xsl:attribute name="Отчество">
											<xsl:value-of select="$Vvar1862_GRD_OfficialsTableDirMiddleName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</ФИО>
						</ОтпускРазреш>
						<Бухгалтер>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_OfficialsTableAccTitle">
									<xsl:variable name="Vvar1869_GRD_OfficialsTableAccTitle_string" select="string(.)" />
									<xsl:attribute name="Должность">
										<xsl:value-of select="$Vvar1869_GRD_OfficialsTableAccTitle_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<ФИО>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableAccLastName">
										<xsl:variable name="Vvar1876_GRD_OfficialsTableAccLastName_string" select="string(.)" />
										<xsl:attribute name="Фамилия">
											<xsl:value-of select="$Vvar1876_GRD_OfficialsTableAccLastName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableAccFirstName">
										<xsl:variable name="Vvar1883_GRD_OfficialsTableAccFirstName_string" select="string(.)" />
										<xsl:attribute name="Имя">
											<xsl:value-of select="$Vvar1883_GRD_OfficialsTableAccFirstName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="n:CustInvoiceJour">
									<xsl:for-each select="n:GRD_OfficialsTableAccMidName">
										<xsl:variable name="Vvar1890_GRD_OfficialsTableAccMiddleName_string" select="string(.)" />
										<xsl:attribute name="Отчество">
											<xsl:value-of select="$Vvar1890_GRD_OfficialsTableAccMiddleName_string" />
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</ФИО>
						</Бухгалтер>
					</ОтпускГруз>
					<ИнфПол>
					<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EDOInfo">
					<xsl:attribute name="ТекстИнф">
									<xsl:value-of select="." />
								</xsl:attribute>
								</xsl:for-each>
								</xsl:for-each>

				</ИнфПол>
				</СвТНО>
				<Подписант>
					<ЮЛ>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoSigningPayINN_RU">
								<xsl:variable name="Vvar1897_GRD_EdoSigningPayINN_RU_string" select="string(.)" />
								<xsl:attribute name="ИННЮЛ">
									<xsl:value-of select="$Vvar1897_GRD_EdoSigningPayINN_RU_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="n:CustInvoiceJour">
							<xsl:for-each select="n:GRD_EdoSigningTitle">
								<xsl:variable name="Vvar1904_GRD_EdoSigningTitle_string" select="string(.)" />
								<xsl:attribute name="Должн">
									<xsl:value-of select="$Vvar1904_GRD_EdoSigningTitle_string" />
								</xsl:attribute>
							</xsl:for-each>
						</xsl:for-each>
						<ФИО>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoSigningLastName">
									<xsl:variable name="Vvar1911_GRD_EdoSigningLastName_string" select="string(.)" />
									<xsl:attribute name="Фамилия">
										<xsl:value-of select="$Vvar1911_GRD_EdoSigningLastName_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoSigningFirstName">
									<xsl:variable name="Vvar1918_GRD_EdoSigningFirstName_string" select="string(.)" />
									<xsl:attribute name="Имя">
										<xsl:value-of select="$Vvar1918_GRD_EdoSigningFirstName_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="n:CustInvoiceJour">
								<xsl:for-each select="n:GRD_EdoSigningMiddleName">
									<xsl:variable name="Vvar1925_GRD_EdoSigningMiddleName_string" select="string(.)" />
									<xsl:attribute name="Отчество">
										<xsl:value-of select="$Vvar1925_GRD_EdoSigningMiddleName_string" />
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</ФИО>
					</ЮЛ>
				</Подписант>
			</Документ>
		</Файл>
	</xsl:template>
</xsl:stylesheet>
<!-- Stylus Studio meta-information - (c) 2004-2009. Progress Software Corporation. All rights reserved.

<metaInformation>
	<scenarios>
		<scenario default="yes" name="AXCustInvoiceJour.xml" userelativepaths="yes" externalpreview="no" url="AXCustInvoiceJour.xml" htmlbaseurl="" outputurl="" processortype="saxon8" useresolver="yes" profilemode="0" profiledepth="" profilelength=""
		          urlprofilexml="" commandline="" additionalpath="" additionalclasspath="" postprocessortype="none" postprocesscommandline="" postprocessadditionalpath="" postprocessgeneratedext="" validateoutput="no" validator="internal"
		          customvalidator="">
			<advancedProp name="sInitialMode" value=""/>
			<advancedProp name="schemaCache" value="||"/>
			<advancedProp name="bXsltOneIsOkay" value="true"/>
			<advancedProp name="bSchemaAware" value="true"/>
			<advancedProp name="bGenerateByteCode" value="true"/>
			<advancedProp name="bXml11" value="false"/>
			<advancedProp name="iValidation" value="0"/>
			<advancedProp name="bExtensions" value="true"/>
			<advancedProp name="iWhitespace" value="0"/>
			<advancedProp name="sInitialTemplate" value=""/>
			<advancedProp name="bTinyTree" value="true"/>
			<advancedProp name="xsltVersion" value="2.0"/>
			<advancedProp name="bWarnings" value="true"/>
			<advancedProp name="bUseDTD" value="false"/>
			<advancedProp name="iErrorHandling" value="fatal"/>
		</scenario>
	</scenarios>
	<MapperMetaTag>
		<MapperInfo srcSchemaPathIsRelative="yes" srcSchemaInterpretAsXML="no" destSchemaPath="" destSchemaRoot="" destSchemaPathIsRelative="yes" destSchemaInterpretAsXML="no">
			<SourceSchema srcSchemaPath="AXCustInvoiceJour.xml" srcSchemaRoot="CustInvoiceJour_GRD" AssociatedInstance="" loaderFunction="document" loaderFunctionUsesURI="no"/>
		</MapperInfo>
		<MapperBlockPosition>
			<template match="/n:CustInvoiceJour_GRD">
				<block path="Файл/xsl:attribute/xsl:value-of" x="278" y="36"/>
				<block path="Файл/xsl:for-each" x="168" y="24"/>
				<block path="Файл/xsl:for-each/xsl:for-each" x="238" y="54"/>
				<block path="Файл/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="318" y="54"/>
				<block path="Файл/xsl:for-each[1]" x="128" y="42"/>
				<block path="Файл/xsl:for-each[1]/xsl:for-each" x="198" y="72"/>
				<block path="Файл/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="72"/>
				<block path="Файл/xsl:for-each[2]" x="88" y="60"/>
				<block path="Файл/xsl:for-each[2]/xsl:for-each" x="238" y="90"/>
				<block path="Файл/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="318" y="90"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each" x="128" y="96"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each/xsl:for-each" x="318" y="126"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="126"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each[1]" x="88" y="114"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each[1]/xsl:for-each" x="198" y="144"/>
				<block path="Файл/СвУчДокОбор/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="238" y="144"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each" x="88" y="150"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each/xsl:for-each" x="318" y="180"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="180"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[1]" x="48" y="208"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[1]/xsl:for-each" x="118" y="198"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="158" y="198"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[2]" x="208" y="186"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[2]/xsl:for-each" x="318" y="216"/>
				<block path="Файл/СвУчДокОбор/СвОЭДОтпрСФ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="216"/>
				<block path="Файл/Документ/xsl:for-each" x="168" y="110"/>
				<block path="Файл/Документ/xsl:for-each/xsl:for-each" x="38" y="60"/>
				<block path="Файл/Документ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="38" y="100"/>
				<block path="Файл/Документ/xsl:for-each[1]" x="128" y="150"/>
				<block path="Файл/Документ/xsl:for-each[1]/xsl:for-each" x="238" y="20"/>
				<block path="Файл/Документ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="318" y="20"/>
				<block path="Файл/Документ/xsl:for-each[2]" x="88" y="150"/>
				<block path="Файл/Документ/xsl:for-each[2]/xsl:for-each" x="38" y="20"/>
				<block path="Файл/Документ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="78" y="20"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Адрес/АдрТекст/xsl:for-each" x="218" y="79"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Адрес/АдрТекст/xsl:for-each/xsl:for-each" x="248" y="109"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Адрес/АдрТекст/xsl:for-each/xsl:for-each/xsl:value-of" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/Контакт/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузОт/ГрузОтпр/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Адрес/АдрТекст/xsl:for-each" x="138" y="239"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Адрес/АдрТекст/xsl:for-each/xsl:for-each" x="248" y="109"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Адрес/АдрТекст/xsl:for-each/xsl:for-each/xsl:value-of" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/Контакт/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ГрузПолуч/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Адрес/АдрТекст/xsl:for-each" x="245" y="40"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Адрес/АдрТекст/xsl:for-each/xsl:for-each" x="275" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Адрес/АдрТекст/xsl:for-each/xsl:for-each/xsl:value-of" x="305" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/Контакт/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Поставщик/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/ИдСв/СвЮЛ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Адрес/АдрТекст/xsl:for-each" x="218" y="79"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Адрес/АдрТекст/xsl:for-each/xsl:for-each" x="248" y="109"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Адрес/АдрТекст/xsl:for-each/xsl:for-each/xsl:value-of" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/Контакт/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Плательщик/БанкРекв/СвБанк/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/Основание/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[1]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[1]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[2]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[2]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[3]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[3]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[4]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[4]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[5]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[5]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[6]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[6]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[7]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[7]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[8]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[8]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[9]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[9]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[10]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[10]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[11]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[11]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[12]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[12]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[13]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[13]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:if" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:if/xsl:attribute/xsl:value-of" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[14]" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/xsl:for-each/xsl:for-each/СвТов/xsl:for-each[14]/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[3]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[3]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[3]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[4]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[4]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[4]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[5]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[5]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/Таблица/ВсегоНакл/xsl:for-each[5]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[3]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[3]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ТН/ТНОбщ/xsl:for-each[3]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/ОтпускРазреш/ФИО/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ОтпускГруз/Бухгалтер/ФИО/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/СвТНО/ИнфПол/xsl:for-each" x="248" y="109"/>
				<block path="Файл/Документ/СвТНО/ИнфПол/xsl:for-each/xsl:for-each" x="278" y="139"/>
				<block path="Файл/Документ/СвТНО/ИнфПол/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="139"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each" x="248" y="70"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[1]" x="248" y="70"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[1]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[1]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[2]" x="248" y="70"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[2]/xsl:for-each" x="278" y="100"/>
				<block path="Файл/Документ/Подписант/ЮЛ/ФИО/xsl:for-each[2]/xsl:for-each/xsl:attribute/xsl:value-of" x="278" y="100"/>
			</template>
		</MapperBlockPosition>
		<TemplateContext></TemplateContext>
		<MapperFilter side="source"></MapperFilter>
	</MapperMetaTag>
</metaInformation>
-->